### PR TITLE
feat: add hide button to calendar events

### LINKED ISSUE #1611: Eyeballs should be on the course icons
I like that you can use the eyeball to hide the page. Make it on the class worksheet colored icons for easier hiding.

https://coursetable.canny.io/admin/board/feature-requests/p/eyeballs-should-be-on-the-course-icons

### PR DESCRIPTION
**Pull request by bearsyankees**
fix #1611

could use some UI tweaks maybe

### CODE REVIEW

**Comment by bearsyankees** [comment]
should probably raise the eye a bit

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
We need to hide the button by default and only show on hover, like the sidebar hide buttons. Also, to ensure contrast between the course color and the button, I suggest you use `chroma` to dynamically calculate the color of the button and inject it through `style`.

**Review by Josh-Cena — APPROVED** [review]

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
Check dark mode; you want to make the icon still black

**Review by Josh-Cena — APPROVED** [review]
LGTM

**Comment by bearsyankees** [comment]
baaannggggggg

**Pull request merged**
