### PR TITLE
User challenge

### LINKED ISSUE #113: Verify access to evaluations data via a user challenge
Will probably require a new backend that can query the ferry graphql API

### PR DESCRIPTION
**Pull request by hsheth2**
Closes #113.

### CODE REVIEW

**Comment by hsheth2** [comment]
When we merge this we'll need to use the create merge commit option instead of rebase

**Comment by hsheth2** [comment]
This is a pretty hefty PR but I think it looks good. @maxyuan6717 lmk what you think

**Comment by maxyuan6717** [comment]
Yah i've been doing some testing and it works really well. One question: do we want to make the user challenge automatically pop up in this PR or add that later cuz rn i have to manually go to the url.

**Comment by hsheth2** [comment]
let's leave that for a separate PR since this one is already massive

**Review by maxyuan6717 — APPROVED** [review]
clean

**Pull request merged**
