### PR TITLE
Use react code-splitting

### PR DESCRIPTION
**Pull request by hsheth2**
Not yet sure if this is a good move

### CODE REVIEW

**Comment by hsheth2** [comment]
@maxyuan6717 curious if you think this is a good idea

I don't really know what the tradeoffs are here

**Comment by maxyuan6717** [comment]
Yah I'm not too familiar with the tradeoffs either, but the overall idea of code splitting seems beneficial in our case. I think it's worth a shot

**Comment by hsheth2** [comment]
Alright i deployed it to the beta site to test it - I feel like it doesn't really help that much since our site isn't that big

**Comment by hsheth2** [comment]
Seems like it broke the home page search, so closing for now

**Pull request closed without merging**
