### PR TITLE
feat: lazy-load route components

### PR DESCRIPTION
**Pull request by Josh-Cena**
Part of an effort to reduce bundle size. This PR makes all page components lazy-loaded, which means unless you are on the respective page, the respective code won't be loaded at all. This speeds up first page load speed, and completely avoids loading heavy dependencies like `graphiql` for 99% of our users.

Before:

image

After:

image

The total size is the same, but note how the main bundle is significantly smaller, and chunks can be loaded on-demand only.

### CODE REVIEW

**Comment by bearsyankees** [comment]
is this that much faster? like at a glance it seems to load at basically the same speed for me as the normal CT but now it just takes a little more time to load the worksheet. But i get your logic here so maybe its worth it even if its just a tiny bit faster

**Comment by Josh-Cena** [comment]
> it seems to load at basically the same speed for me as the normal CT

It's only noticeable on slower network indeed, but the point is we can now more easily optimize because there aren't as many critical dependencies, and subpages can use whatever heavy dependencies they want and those don't get loaded by default.

>  it just takes a little more time to load the worksheet

Yeah, I'll take some more time to check this. We need to preload the chunks so React never renders the loading screen at all. Not sure how to do that with suspense.

**Comment by Josh-Cena** [comment]
@bearsyankees I fixed this by eagerly fetching Catalog/Worksheet instead.

**Comment by bearsyankees** [comment]
ok ya this is way better. nice!!

**Pull request merged**
