### PR TITLE
Add react-tour onboarding functionality

### PR DESCRIPTION
**Pull request by itsjoshthedeveloper**
So first time users can learn how to use the new design

- [x] Add all steps of react tour
- [x] Fix isComponentVisible event handler
- [x] Save in local storage
- [x] Add tutorial nav link
- [x] Fix advanced react selects not opening in tutorial
- [x] Prevent scrolling
- [x] Add custom back & next buttons (with themed styles)
- [x] Show dot nav and close btn if not first time
- [x] Add heading for each step (like Miro)
- [x] Add videos
- [x] Add illustrations
- [x] Add feedback video

### CODE REVIEW

**Comment by itsjoshthedeveloper** [comment]
- [x] Add all steps of react tour
- [ ] Fix isComponentVisible event handler

**Comment by itsjoshthedeveloper** [comment]
@maxyuan6717 @kevinhu there's no problems with me putting videos and images in the `public` folder correct? or is it better for me to keep it in the `src` folder?

**Comment by maxyuan6717** [comment]
hmm, if the videos show catalog stuff, it should technically be private, but idk if it matters too much

**Comment by itsjoshthedeveloper** [comment]
> hmm, if the videos show catalog stuff, it should technically be private, but idk if it matters too much

lmk if you want me to change it in the future

**Comment by itsjoshthedeveloper** [comment]
@kevinhu do you know why the vercel deploy is failing?

**Pull request merged**
