### PR TITLE
Add some small text fixes

### PR DESCRIPTION
**Pull request by itsjoshthedeveloper**
- [x] Change 'Reset Filters' label to 'Reset'
- [x] Add full names for skills, areas, and schools
- [x] Add colors for skills/areas in popout btn
- [x] Use grouped options in react-select for skills and areas

### CODE REVIEW

**Comment by itsjoshthedeveloper** [comment]
@michemli @maxyuan6717 what do ya'll think?

larger-filter-names

**Review by maxyuan6717 — APPROVED** [review]
noice

**Comment by itsjoshthedeveloper** [comment]
@michemli can you review again?

areas-skills-preview-1

**Comment by michemli** [comment]
@itsjoshthedeveloper looks good!!

**Review by michemli — APPROVED** [review]

**Pull request merged**
