### PR TITLE
chore: React 18, react-router 6

### PR DESCRIPTION
**Pull request by Josh-Cena**
@bearsyankees Please help me test this—there could be breaking changes I didn't catch.

### CODE REVIEW

**Review by bearsyankees — CHANGES_REQUESTED** [review]
check conflicts then i will merge the other one once its fine then tackle this one

**Comment by Josh-Cena** [comment]
Will check the conflicts after https://github.com/coursetable/coursetable/pull/1361 is merged, since there will be a lot more.

**Review by bearsyankees — APPROVED** [review]
way to go man. great stuff.

**Comment by Josh-Cena** [comment]
@bearsyankees The error makes no sense to me since there's no `MyRoute` in the entire codebase now. Can I have access to the Sentry logs?

**Pull request merged**
