### PR TITLE
Implement new catalog design

### PR DESCRIPTION
**Pull request by itsjoshthedeveloper**
DO NOT MERGE TO MASTER. Just a placeholder until we figure out where to actually merge this branch in order to deploy to [beta.coursetable.com](https://beta.coursetable.com)

### CODE REVIEW

**Comment by itsjoshthedeveloper** [comment]
@maxyuan6717 i'm having an issue with the `CustomSelect` menu... do you know how to keep it open permanently so it is there already when we open the dropdown but also have it disappear when we close the dropdown? i've tried setting the `menuIsOpen` prop to `true` and changing the menu's position to `static` but that didn't work. i also tried setting `menuIsOpen` dynamically, but that didn't work either.

filter_dropdown_menu

**Comment by itsjoshthedeveloper** [comment]
nvm, i got it!

filter_dropdown_menu_fixed

**Comment by itsjoshthedeveloper** [comment]
@maxyuan6717 @kevinhu do ya'll know why the frontend check is failing?

**Comment by maxyuan6717** [comment]
hmm yah the logs aren't rlly saying much

**Comment by hsheth2** [comment]
@itsjoshthedeveloper the site should be deployed to beta.coursetable.com :) - @kevinhu also knows how to redeploy it

**Pull request merged**
