### PR TITLE
feat: show percentage of enrolled students who left review

### PR DESCRIPTION
**Pull request by Josh-Cena**
Fix https://github.com/coursetable/coursetable/issues/1620

### CODE REVIEW

**Comment by bearsyankees** [comment]
Looks good but i think we should make it even more prominent, and maybe somehow show it also on the catalog page (maybe as a tooltip hover on the overall/work/prof)?

**Comment by Josh-Cena** [comment]
@bearsyankees The catalog view shows average across seasons, not this particular offering.

**Comment by bearsyankees** [comment]
> @bearsyankees The catalog view shows average across seasons, not this particular offering.

yea, could do for all time but i agree not ideal, i just think its a good stat to display more prominently, ill think on where best to put it. unless you think as is is ideal

**Comment by Josh-Cena** [comment]
FWIW, I don't find this metric extremely useful, because lower percentage doesn't mean less credible scores; it's the _number_ that matters more. For the overview, we would need much more sophisticated statistics.

**Comment by Josh-Cena** [comment]
@bearsyankees Good to merge?

**Comment by bearsyankees** [comment]
Yeah LGTM, can always adjust later

**Review by bearsyankees — APPROVED** [review]

**Pull request merged**
