### PR TITLE
Course Info

### PR DESCRIPTION
**Pull request by hsheth2**
- Adds data to the modal for:
  - `flag_info` (course information)
  - `classnotes`
  - `regnotes`
  - `rp_attr` (reading period)
  - `final_exam`
- Fixes enrollment numbers in catalog and modal.
- Adds ability to sort by (rating - workload) aka gut rating.

### CODE REVIEW

**Comment by hsheth2** [comment]
fyi - I'm planning redeploying once this is merged

**Review by maxyuan6717 — APPROVED** [review]
Looks good. I just removed the 0 that gets printed if there is no course info.

**Review by kevinhu — APPROVED** [review]
Runs cleanly on my end - was going to note the '0' but looks like Max fixed it.

**Comment by hsheth2** [comment]
Slipped in a quick change that adds the sort by (rating - workload) value - we can work on a real "gut" rating at some point in the future lol

**Pull request merged**
