### PR TITLE
feat: student reviews on landing page

### PR DESCRIPTION
**Pull request by bearsyankees**
Could be nice... (pulled from buymeacoffee)

### CODE REVIEW

**Comment by bearsyankees** [comment]
@Josh-Cena thoughts

**Comment by Josh-Cena** [comment]
As we discussed a while ago, we should at least provide a link to the original buymeacoffee page. Also maybe the two about "paying" aren't really appropriate.

**Comment by bearsyankees** [comment]
@Josh-Cena look good 2 merge?

**Review by Josh-Cena — APPROVED** [review]
This is awesome let's go

**Comment by Josh-Cena** [comment]
I think we should get a designer to remake the landing page. Looks a bit plain, WDYT?

**Pull request merged**
