### PR TITLE
Crop ® and padding out of LinkedIn logo

### LINKED ISSUE #1679: LinkedIn icons on team page should be cleaner
Take out the ® pls

### PR DESCRIPTION
**Pull request by ErikBoesen**
Fixes #1679

### CODE REVIEW

**Comment by ErikBoesen** [comment]
I have decided on a hidden motive

**Comment by bearsyankees** [comment]
> I have decided on a hidden motive

Hahahaa i was about to say. this is like XZ. but yes fair enough... wonder why prev is failing maybe bc ur not part of vercel so i need to make a commit or somethin

**Comment by bearsyankees** [comment]
(run bun lint and should be good to go or i can)

**Comment by Josh-Cena** [comment]
Somehow both files have tripled in size 🤷‍♂️ Eric can you confirm you are not planting backdoors in the PNG?

I'm not sure why `actions/checkout` refuses to checkout your fork, though.

**Review by Josh-Cena — APPROVED** [review]
Better after opmization :) I guess your headshot is just now less compressable.

**Comment by Josh-Cena** [comment]
I don't think our CD can deploy previews from forks—that's a good thing, becaue otherwise our Doppler secrets might leak.

**Comment by bearsyankees** [comment]
Lets hope no backdoors...

**Pull request merged**
