### PR TITLE
refactor: reorganize About page

### PR DESCRIPTION
**Pull request by neilsong**
Initial motivation: One of the former leads told me he still gets contacted about Coursetable feat reqs and would like to be moved to the alumni section to prevent this. 

2 major changes:
 - Moved former leads to alumni section
 - Reorganized alumni section
   - Alumni are grouped by their roles
   - Ordering is now best guess reverse chronological

### CODE REVIEW

**Comment by neilsong** [comment]
@bearsyankees I moved Erik to alumni - I assume that's fine?

**Comment by bearsyankees** [comment]
LGTM but lets make it CofounderS and LeadS etc. will send a message!

**Comment by neilsong** [comment]
RIP the elegance of my filter component 😭
But sure, I'll add it.

**Comment by bearsyankees** [comment]
Hahahaha yep. They all end with s so u can add pretty easily i bet

**Comment by neilsong** [comment]
But what about "design" and "development"

**Comment by bearsyankees** [comment]
add a current team header too i would say

**Review by bearsyankees — APPROVED** [review]

**Review by Josh-Cena — APPROVED** [review]
LGTM

**Comment by neilsong** [comment]
Will merge on Friday to give everyone time to get their headshot in

**Pull request merged**
