### PR TITLE
feat: search location

### PR DESCRIPTION
**Pull request by Josh-Cena**
Part of https://github.com/coursetable/coursetable/issues/1453

### CODE REVIEW

**Comment by bearsyankees** [comment]
LGTM but do we want a toggle for this or just alwayson?

**Comment by Josh-Cena** [comment]
I implemented this in a way that shouldn't cause any confusion. The building names almost always never collides with other useful information, so we can just do this.

**Comment by bearsyankees** [comment]
Ok yeah. How should we alert people that this is an option now though

**Comment by Josh-Cena** [comment]
> How should we alert people that this is an option now though

I mean... The text box says "or whatever we don't care" so they know when they try?

**Comment by bearsyankees** [comment]
I guess but I feel like no one will wake up and try by location.... but I don't see an amazing solution

**Comment by Josh-Cena** [comment]
I mean... I've tried, because I thought all displayed text is searchable. I guess that's a reasonable expectation. Few people probably need this anyway. (I needed this because I often wonder who is having class in our classroom before and after a class.)

**Comment by bearsyankees** [comment]
OKEDOKE i give in

**Pull request merged**
