### PR TITLE
Fix padding of catalog stuff

### PR DESCRIPTION
**Pull request by maxyuan6717**

### CODE REVIEW

**Review by itsjoshthedeveloper — CHANGES_REQUESTED** [review]
@maxyuan6717 the problems that i was talking about in #454 are shown in the gif below.

catalog-fix

more specifically, they are:
- the FB# gets pushed to the next row when coming from the worksheet
- the search results are not in the `SurfaceComponent` so the card view shows the cards without a background
- the expanded catalog view results don't have `mx-auto`, so they expand to the full width of the catalog

these are due to the changes found in 9908ed7a58fba8d02df94d323f45c038a64f7e45. i made these changes to fix the sticky headers for the search results but that resulted in the problems listed above.

**Comment by maxyuan6717** [comment]
Ah interesting; Issues 1&3 don't happen on my screen width, so I missed them, but tis a quick fix

**Review by itsjoshthedeveloper — COMMENTED** [review]
awesome, that looks great! the 1st issue was still there, so I decreased the width of the title column by 10px to prevent the FB# from overflowing.

**Review by itsjoshthedeveloper — APPROVED** [review]

**Comment by itsjoshthedeveloper** [comment]
🙌

**Comment by itsjoshthedeveloper** [comment]
@hsheth2 just noticed that you deployed the old version of `master`. this PR fixes the searchResults component bug, so can you deploy the branch after this merge instead?

**Comment by hsheth2** [comment]
@itsjoshthedeveloper yep the latest master is now deployed

**Pull request merged**
